### ISSUE TITLE
Add ::PP to namespace

### ISSUE THREAD

**Issue by leejo** [athenahealth/net-amqp-rabbitmq#15]
There now exists another module with the same namespace as this module:

https://metacpan.org/pod/Net::AMQP::RabbitMQ

https://github.com/markwellis/net-amqp-rabbitmq

Suggest changing the namespace of this module to:

Net::AMQP::RabbitMQ::PP

To prevent any future issues and make clear that this version is a pure perl implementation.

**Comment by emarcotte** [comment]
Should probably rename the repo, but this was merged a while ago so I'm going to close this.
