### ISSUE TITLE
This module is not available on CPAN

### ISSUE THREAD

**Issue by leejo** [athenahealth/net-amqp-rabbitmq#17]
I'm updating our version of perl and when i go looking for this module it can't be found on CPAN. Suggest actually uploading it there and not just relying on github.

**Comment by zbentley** [comment]
I don't think this module is used by athena code, or is complete and/or under development any more. Ask @emarcotte to be sure though.

**Comment by leejo** [comment]
@emarcotte @athenahealth - is this module abandonware? want me to take over maintenance?

**Comment by emarcotte** [comment]
Go for it. We never got a chance to deploy it

**Comment by leejo** [comment]
OK, will do. Thanks.
